name: Ubuntu

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CPM_SOURCE_CACHE: ${{ github.workspace }}/cpm_modules
  BUILD_TYPE: Release

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: cache Conan dependencies
        id: cache-conan
        uses: actions/cache@v2
        with:
          path: path/to/.conan2
          key: ${{ runner.os }}-conan-${{ hashFiles('**/conanfile.py') }}
      
      - name: install Conan
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip
          pip3 install conan

      # if we did hit the cache, then you do not want to create a new default  
      # profile since you already have one
      - if: ${{ steps.cache-conan.outputs.cache-hit != 'true' }}
        name: configure Conan
        run: conan profile detect --force

      - name: Conan profile load
        run:  |
          conan profile detect
          conan profile show

      - name: install dependencies
        run: conan install . -s build_type=${{env.BUILD_TYPE}} -of=${{github.workspace}}/build -pr default -b=missing
      
      - name: configureLibrary
        run: cmake -B ${{github.workspace}}/build -DCMAKE_TOOLCHAIN_FILE=conan_toolchain.cmake -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
      
      - name: makeLibrary
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
      
      - name: configureStandalone
        run: cmake -S ./Standalone -B ${{github.workspace}}/build/Standalone -DCMAKE_TOOLCHAIN_FILE=../conan_toolchain.cmake -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
        
      - name: makeStandalone
        run: cmake --build ${{github.workspace}}/build/Standalone --config ${{env.BUILD_TYPE}}
