name: Ubuntu

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CPM_SOURCE_CACHE: ${{ github.workspace }}/cpm_modules

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Conan
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip
          pip3 install conan

      - name: Configure Conan
        run: conan profile detect --force

      - name: Install dependencies
        run: conan install . --build=missing

      - name: configureLibrary
        run: cmake -S . -B Build/Library/Debug -DCMAKE_BUILD_TYPE=Debug -DCMAKE_PREFIX_PATH=$CONAN_PREFIX_PATH
      - name: makeLibrary
        run: cmake --build Build/Library/Debug --target all
      - name: configureStandalone
        run: cmake -S ./Standalone -B Build/Standalone/Debug -DCMAKE_BUILD_TYPE=Debug
      - name: makeStandalone
        run: cmake --build Build/Standalone/Debug --target all